name: transpiler-tests
on:
  push:
  workflow_dispatch:
jobs:
  transformations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ivy
          persist-credentials: false
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run Transformations Tests
        id: tests
        run: |
          cd ivy
          docker run --rm -v "$(pwd)":/ivy ivyllc/ivy:latest python3 -m pytest ivy_tests/test_transpiler/transformations -p no:warnings
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
